-- ============================================================
-- YC Hack — Full Schema
-- ============================================================

-- ============================================================
-- JOBS
-- Top-level job record created when the user submits a problem
-- on the frontend. The orchestrator agent is embedded as JSON.
-- ============================================================
CREATE TABLE jobs (
  id                 UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  problem            TEXT        NOT NULL,
  worker_count       INTEGER     NOT NULL DEFAULT 1,
  deadline           TEXT,
  linq_phone         TEXT,
  status             TEXT        NOT NULL DEFAULT 'generating'
                                 CHECK (status IN ('generating', 'deploying', 'running', 'done', 'failed')),
  -- Full orchestrator agent config / state stored as JSON
  orchestrator_agent JSONB       NOT NULL DEFAULT '{}',
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- WORKER_AGENTS
-- One row per worker slot in a job. The orchestrator points to
-- each worker via job_id. Full agent config stored as JSON.
-- ============================================================
CREATE TABLE worker_agents (
  id                   UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id               UUID        NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
  worker_index         INTEGER     NOT NULL,          -- 0-based position
  subtask_title        TEXT        NOT NULL,
  -- Full agent config: perspective, instructions, acceptance criteria, etc.
  config               JSONB       NOT NULL DEFAULT '{}',
  status               TEXT        NOT NULL DEFAULT 'pending'
                                   CHECK (status IN ('pending', 'in-progress', 'review', 'done', 'blocked')),
  linq_conversation_id TEXT,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX ON worker_agents (job_id);

-- ============================================================
-- AGENT_FILES
-- Markdown and JSON files generated by the orchestrator or
-- worker agents. worker_agent_id = NULL means orchestrator file.
-- ============================================================
CREATE TABLE agent_files (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id           UUID        NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
  -- NULL = generated by the orchestrator
  worker_agent_id  UUID        REFERENCES worker_agents(id) ON DELETE SET NULL,
  filename         TEXT        NOT NULL,
  file_type        TEXT        NOT NULL CHECK (file_type IN ('md', 'json')),
  content          TEXT        NOT NULL,
  size_label       TEXT,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX ON agent_files (job_id);
CREATE INDEX ON agent_files (worker_agent_id);

-- ============================================================
-- Context Graph Schema
-- ============================================================
-- Enable pgvector for semantic search across graph nodes
CREATE EXTENSION IF NOT EXISTS vector;

-- ============================================================
-- RESEARCH JOBS
-- Top-level research task dispatched to a fleet of agents
-- ============================================================
CREATE TABLE research_jobs (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  title       TEXT        NOT NULL,
  description TEXT,
  status      TEXT        NOT NULL DEFAULT 'pending'
                          CHECK (status IN ('pending', 'running', 'synthesizing', 'done', 'failed')),
  metadata    JSONB       NOT NULL DEFAULT '{}',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- AGENTS
-- Worker agents deployed for a job, each with a distinct perspective.
-- e.g. perspective = 'technical' | 'ethical' | 'economic' | 'historical'
-- ============================================================
CREATE TABLE agents (
  id                    UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id                UUID        NOT NULL REFERENCES research_jobs(id) ON DELETE CASCADE,
  name                  TEXT        NOT NULL,
  perspective           TEXT        NOT NULL,
  role                  TEXT        NOT NULL DEFAULT 'researcher'
                                    CHECK (role IN ('orchestrator', 'researcher', 'synthesizer')),
  status                TEXT        NOT NULL DEFAULT 'idle'
                                    CHECK (status IN ('idle', 'running', 'done', 'failed')),
  linq_conversation_id  TEXT,
  metadata              JSONB       NOT NULL DEFAULT '{}',
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- CONTEXT NODES
-- Individual knowledge units that make up the graph.
-- Each node is a discrete piece of information contributed by one or more agents.
-- ============================================================
CREATE TABLE context_nodes (
  id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id       UUID        NOT NULL REFERENCES research_jobs(id) ON DELETE CASCADE,
  type         TEXT        NOT NULL
                           CHECK (type IN ('fact', 'claim', 'hypothesis', 'question', 'concept', 'synthesis')),
  title        TEXT,
  content      TEXT        NOT NULL,
  -- Confidence score [0,1] — higher = more agents endorsed, fewer disputes
  confidence   FLOAT       CHECK (confidence >= 0 AND confidence <= 1),
  source_url   TEXT,
  source_label TEXT,
  -- 1536-dim embedding for pgvector semantic search (OpenAI/Claude embeddings)
  embedding    VECTOR(1536),
  metadata     JSONB       NOT NULL DEFAULT '{}',
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for fast ANN (approximate nearest neighbor) semantic search
CREATE INDEX ON context_nodes USING ivfflat (embedding vector_cosine_ops)
  WITH (lists = 100);

-- ============================================================
-- CONTEXT EDGES
-- Directed, typed relationships between nodes.
-- Build the actual graph structure that agents traverse/contribute to.
-- ============================================================
CREATE TABLE context_edges (
  id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id         UUID        NOT NULL REFERENCES research_jobs(id) ON DELETE CASCADE,
  source_node_id UUID        NOT NULL REFERENCES context_nodes(id) ON DELETE CASCADE,
  target_node_id UUID        NOT NULL REFERENCES context_nodes(id) ON DELETE CASCADE,
  type           TEXT        NOT NULL
                             CHECK (type IN (
                               'supports',     -- A strengthens B
                               'contradicts',  -- A conflicts with B
                               'relates_to',   -- general association
                               'causes',       -- A causes B
                               'depends_on',   -- A requires B to hold
                               'similar_to',   -- semantic similarity
                               'refines',      -- A elaborates/narrows B
                               'derived_from'  -- A was synthesized from B
                             )),
  -- Edge weight [0,1] — strength of the relationship
  weight         FLOAT       NOT NULL DEFAULT 1.0 CHECK (weight >= 0 AND weight <= 1),
  metadata       JSONB       NOT NULL DEFAULT '{}',
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT no_self_loops CHECK (source_node_id != target_node_id)
);

CREATE INDEX ON context_edges (source_node_id);
CREATE INDEX ON context_edges (target_node_id);
CREATE INDEX ON context_edges (job_id, type);

-- ============================================================
-- AGENT CONTRIBUTIONS
-- Join table recording which agent contributed which node/edge,
-- their perspective at the time, and any reasoning they provided.
-- contribution_type:
--   created  — agent authored the node/edge
--   endorsed — agent independently validated an existing node/edge
--   disputed — agent flagged a node/edge as inaccurate from their perspective
--   refined  — agent updated content/confidence of an existing node/edge
-- ============================================================
CREATE TABLE agent_contributions (
  id                UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  agent_id          UUID        NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
  job_id            UUID        NOT NULL REFERENCES research_jobs(id) ON DELETE CASCADE,
  node_id           UUID        REFERENCES context_nodes(id) ON DELETE CASCADE,
  edge_id           UUID        REFERENCES context_edges(id) ON DELETE CASCADE,
  contribution_type TEXT        NOT NULL
                                CHECK (contribution_type IN ('created', 'endorsed', 'disputed', 'refined')),
  -- Free-text reasoning the agent provided when making this contribution
  reasoning         TEXT,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  -- Each contribution targets exactly one node OR one edge
  CONSTRAINT node_or_edge CHECK (
    (node_id IS NOT NULL AND edge_id IS NULL) OR
    (node_id IS NULL AND edge_id IS NOT NULL)
  )
);

CREATE INDEX ON agent_contributions (job_id, node_id);
CREATE INDEX ON agent_contributions (job_id, edge_id);
CREATE INDEX ON agent_contributions (agent_id);

-- ============================================================
-- LINQ CONVERSATIONS
-- Messaging channels between agents and workers (or the PM)
-- ============================================================
CREATE TABLE linq_conversations (
  id             TEXT        PRIMARY KEY,   -- Linq-assigned ID
  job_id         UUID        NOT NULL REFERENCES research_jobs(id) ON DELETE CASCADE,
  agent_id       UUID        REFERENCES agents(id) ON DELETE SET NULL,
  is_pm_channel  BOOLEAN     NOT NULL DEFAULT FALSE,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- LINQ MESSAGES
-- Individual messages within a conversation, synced locally
-- ============================================================
CREATE TABLE linq_messages (
  id               TEXT        PRIMARY KEY,  -- Linq-assigned ID
  conversation_id  TEXT        NOT NULL REFERENCES linq_conversations(id) ON DELETE CASCADE,
  sender           TEXT        NOT NULL CHECK (sender IN ('agent', 'worker', 'pm')),
  content          TEXT        NOT NULL,
  attachments      JSONB       NOT NULL DEFAULT '[]',
  -- Classified by the Worker Agent via Claude
  classified_type  TEXT        CHECK (classified_type IN ('question', 'progress', 'blocker', 'completion')),
  timestamp        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX ON linq_messages (conversation_id, timestamp);

-- ============================================================
-- AGENT LOGS
-- Append-only audit trail of every agent action
-- ============================================================
CREATE TABLE agent_logs (
  id          BIGINT      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  timestamp   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  job_id      UUID        NOT NULL REFERENCES research_jobs(id) ON DELETE CASCADE,
  agent_id    UUID        NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
  -- e.g. 'decompose', 'send_message', 'add_node', 'add_edge', 'endorse_node', 'submit_deliverable'
  action      TEXT        NOT NULL,
  payload     JSONB,
  tokens_used INTEGER
);

CREATE INDEX ON agent_logs (job_id, timestamp);
CREATE INDEX ON agent_logs (agent_id, timestamp);

-- ============================================================
-- HELPERS: auto-update updated_at
-- ============================================================
CREATE OR REPLACE FUNCTION touch_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_jobs_updated_at
  BEFORE UPDATE ON jobs
  FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE TRIGGER trg_agent_files_updated_at
  BEFORE UPDATE ON agent_files
  FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE TRIGGER trg_research_jobs_updated_at
  BEFORE UPDATE ON research_jobs
  FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE TRIGGER trg_context_nodes_updated_at
  BEFORE UPDATE ON context_nodes
  FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ============================================================
-- VIEWS
-- ============================================================

-- Node contribution summary — how many agents endorsed vs disputed each node
CREATE VIEW node_consensus AS
SELECT
  n.id                                          AS node_id,
  n.job_id,
  n.type,
  n.title,
  n.content,
  n.confidence,
  COUNT(*) FILTER (WHERE ac.contribution_type = 'created')   AS created_by,
  COUNT(*) FILTER (WHERE ac.contribution_type = 'endorsed')  AS endorsements,
  COUNT(*) FILTER (WHERE ac.contribution_type = 'disputed')  AS disputes,
  COUNT(*) FILTER (WHERE ac.contribution_type = 'refined')   AS refinements,
  -- Agents that endorsed this node (array of perspectives)
  ARRAY_AGG(DISTINCT a.perspective) FILTER (
    WHERE ac.contribution_type IN ('created', 'endorsed')
  )                                             AS endorsing_perspectives
FROM context_nodes n
LEFT JOIN agent_contributions ac ON ac.node_id = n.id
LEFT JOIN agents a ON a.id = ac.agent_id
GROUP BY n.id;

-- Graph edge summary for a job — useful for frontend graph rendering
CREATE VIEW graph_edges_view AS
SELECT
  e.id,
  e.job_id,
  e.type,
  e.weight,
  src.id    AS source_id,
  src.type  AS source_type,
  src.title AS source_title,
  tgt.id    AS target_id,
  tgt.type  AS target_type,
  tgt.title AS target_title
FROM context_edges e
JOIN context_nodes src ON src.id = e.source_node_id
JOIN context_nodes tgt ON tgt.id = e.target_node_id;
